import type { AppLocale } from "./supportedLocales";

type ProgressCopyKey =
  | "title"
  | "prepare"
  | "investigate"
  | "discuss"
  | "audit"
  | "publish"
  | "prepareDetail"
  | "investigateDetail"
  | "discussDetail"
  | "auditDetail"
  | "publishDetail"
  | "working"
  | "queued"
  | "reconnecting"
  | "cancelling"
  | "cancelled"
  | "failed"
  | "incomplete"
  | "published"
  | "queuedDetail"
  | "reconnectingDetail"
  | "cancellingDetail"
  | "cancelledDetail"
  | "failedDetail"
  | "incompleteDetail"
  | "publishedDetail"
  | "done"
  | "current"
  | "upcoming";

export const researchProgressCopy = {
  en: {
    title: "Research progress",
    prepare: "Prepare evidence",
    investigate: "Independent research",
    discuss: "Team review",
    audit: "Evidence audit",
    publish: "Publish report",
    prepareDetail: "Collecting and organizing sources for the research team.",
    investigateDetail: "Agents are independently examining the evidence.",
    discussDetail: "Teams are comparing findings and testing counterarguments.",
    auditDetail: "Checking the evidence and source links behind the findings.",
    publishDetail: "The committee is synthesizing the report for publication.",
    working: "In progress",
    queued: "Queued",
    reconnecting: "Reconnecting",
    cancelling: "Cancelling",
    cancelled: "Cancelled",
    failed: "Stopped",
    incomplete: "Needs recovery",
    published: "Published",
    queuedDetail: "Waiting for research capacity.",
    reconnectingDetail: "Checking the latest server status.",
    cancellingDetail: "Stopping the current research safely.",
    cancelledDetail: "This research was cancelled.",
    failedDetail: "Research stopped. Completed work has been preserved.",
    incompleteDetail: "Completed work is preserved for recovery.",
    publishedDetail: "Your research report has been published.",
    done: "Completed",
    current: "Current stage",
    upcoming: "Upcoming",
  },
  ko: {
    title: "리서치 진행 상황",
    prepare: "자료 준비",
    investigate: "독립 조사",
    discuss: "팀 검토",
    audit: "근거 검토",
    publish: "보고서 발행",
    prepareDetail: "조사에 필요한 자료를 수집하고 정리하고 있어요.",
    investigateDetail: "에이전트가 각자의 관점에서 근거를 조사하고 있어요.",
    discussDetail: "팀별 조사 결과를 비교하고 반론을 검토하고 있어요.",
    auditDetail: "분석을 뒷받침하는 근거와 출처를 확인하고 있어요.",
    publishDetail: "위원회가 최종 의견을 정리하고 보고서를 준비하고 있어요.",
    working: "진행 중",
    queued: "대기 중",
    reconnecting: "다시 연결 중",
    cancelling: "취소 중",
    cancelled: "취소됨",
    failed: "중단됨",
    incomplete: "복구 필요",
    published: "발행 완료",
    queuedDetail: "리서치를 시작할 수 있도록 순서를 기다리고 있어요.",
    reconnectingDetail: "서버의 최신 진행 상태를 확인하고 있어요.",
    cancellingDetail: "현재 리서치를 안전하게 중단하고 있어요.",
    cancelledDetail: "리서치가 취소되었습니다.",
    failedDetail: "리서치가 중단되었습니다. 완료된 작업은 보존됩니다.",
    incompleteDetail: "완료된 작업이 보존되어 다시 진행할 수 있어요.",
    publishedDetail: "리서치 보고서가 발행되었습니다.",
    done: "완료",
    current: "현재 단계",
    upcoming: "예정",
  },
  ja: {
    title: "リサーチの進捗",
    prepare: "資料準備",
    investigate: "独立調査",
    discuss: "チーム検討",
    audit: "根拠確認",
    publish: "レポート公開",
    prepareDetail: "調査に必要な資料を収集・整理しています。",
    investigateDetail: "各エージェントが独立して根拠を調査しています。",
    discussDetail: "チームの調査結果を比較し、反論を検討しています。",
    auditDetail: "分析の根拠と出典を確認しています。",
    publishDetail: "委員会が最終見解をまとめ、公開の準備をしています。",
    working: "進行中",
    queued: "待機中",
    reconnecting: "再接続中",
    cancelling: "キャンセル中",
    cancelled: "キャンセル済み",
    failed: "停止",
    incomplete: "復旧が必要",
    published: "公開済み",
    queuedDetail: "調査を開始できるまで待機しています。",
    reconnectingDetail: "サーバーの最新状況を確認しています。",
    cancellingDetail: "調査を安全に停止しています。",
    cancelledDetail: "調査はキャンセルされました。",
    failedDetail: "調査が停止しました。完了した作業は保存されています。",
    incompleteDetail: "完了した作業は保存されており、再開できます。",
    publishedDetail: "リサーチレポートが公開されました。",
    done: "完了",
    current: "現在の段階",
    upcoming: "今後",
  },
  "zh-TW": {
    title: "研究進度",
    prepare: "準備資料",
    investigate: "獨立研究",
    discuss: "團隊審議",
    audit: "查核依據",
    publish: "發布報告",
    prepareDetail: "正在收集並整理研究所需的資料。",
    investigateDetail: "各代理正在獨立分析研究依據。",
    discussDetail: "團隊正在比較研究結果並檢視反方論點。",
    auditDetail: "正在確認分析依據及來源連結。",
    publishDetail: "委員會正在彙整最終意見並準備發布報告。",
    working: "進行中",
    queued: "排隊中",
    reconnecting: "重新連線中",
    cancelling: "取消中",
    cancelled: "已取消",
    failed: "已停止",
    incomplete: "需要恢復",
    published: "已發布",
    queuedDetail: "正在等待研究處理名額。",
    reconnectingDetail: "正在確認伺服器上的最新進度。",
    cancellingDetail: "正在安全停止目前的研究。",
    cancelledDetail: "研究已取消。",
    failedDetail: "研究已停止，已完成的工作仍會保留。",
    incompleteDetail: "已完成的工作已保留，可繼續進行。",
    publishedDetail: "研究報告已發布。",
    done: "已完成",
    current: "目前階段",
    upcoming: "即將進行",
  },
  es: {
    title: "Progreso del análisis",
    prepare: "Preparación",
    investigate: "Investigación",
    discuss: "Revisión del equipo",
    audit: "Verificación",
    publish: "Publicación",
    prepareDetail: "Recopilando y organizando las fuentes para el equipo.",
    investigateDetail:
      "Los agentes están examinando las pruebas de forma independiente.",
    discussDetail:
      "Los equipos comparan resultados y evalúan contraargumentos.",
    auditDetail: "Verificando las pruebas y las fuentes de los resultados.",
    publishDetail: "El comité está preparando el informe para su publicación.",
    working: "En curso",
    queued: "En espera",
    reconnecting: "Reconectando",
    cancelling: "Cancelando",
    cancelled: "Cancelado",
    failed: "Detenido",
    incomplete: "Requiere recuperación",
    published: "Publicado",
    queuedDetail: "Esperando capacidad para iniciar la investigación.",
    reconnectingDetail: "Consultando el estado más reciente del servidor.",
    cancellingDetail: "Deteniendo la investigación de forma segura.",
    cancelledDetail: "La investigación se canceló.",
    failedDetail:
      "La investigación se detuvo. El trabajo completado se conserva.",
    incompleteDetail:
      "El trabajo completado se conserva para poder reanudarlo.",
    publishedDetail: "El informe de investigación se ha publicado.",
    done: "Completado",
    current: "Etapa actual",
    upcoming: "Próximamente",
  },
  "pt-BR": {
    title: "Progresso da pesquisa",
    prepare: "Preparação",
    investigate: "Investigação",
    discuss: "Revisão da equipe",
    audit: "Verificação",
    publish: "Publicação",
    prepareDetail: "Coletando e organizando fontes para a equipe.",
    investigateDetail:
      "Os agentes estão examinando as evidências de forma independente.",
    discussDetail: "As equipes comparam resultados e avaliam contrapontos.",
    auditDetail: "Verificando as evidências e as fontes dos resultados.",
    publishDetail: "O comitê está preparando o relatório para publicação.",
    working: "Em andamento",
    queued: "Na fila",
    reconnecting: "Reconectando",
    cancelling: "Cancelando",
    cancelled: "Cancelada",
    failed: "Interrompida",
    incomplete: "Requer recuperação",
    published: "Publicado",
    queuedDetail: "Aguardando capacidade para iniciar a pesquisa.",
    reconnectingDetail: "Verificando o estado mais recente no servidor.",
    cancellingDetail: "Interrompendo a pesquisa com segurança.",
    cancelledDetail: "A pesquisa foi cancelada.",
    failedDetail:
      "A pesquisa foi interrompida. O trabalho concluído foi preservado.",
    incompleteDetail: "O trabalho concluído foi preservado para retomada.",
    publishedDetail: "O relatório de pesquisa foi publicado.",
    done: "Concluído",
    current: "Etapa atual",
    upcoming: "A seguir",
  },
  de: {
    title: "Recherchefortschritt",
    prepare: "Vorbereitung",
    investigate: "Einzelrecherche",
    discuss: "Teamprüfung",
    audit: "Belegprüfung",
    publish: "Veröffentlichung",
    prepareDetail:
      "Quellen werden für das Rechercheteam gesammelt und geordnet.",
    investigateDetail:
      "Die Agenten untersuchen die Belege unabhängig voneinander.",
    discussDetail:
      "Die Teams vergleichen Ergebnisse und prüfen Gegenargumente.",
    auditDetail: "Belege und Quellen der Ergebnisse werden überprüft.",
    publishDetail: "Das Komitee bereitet den Bericht zur Veröffentlichung vor.",
    working: "In Bearbeitung",
    queued: "In Warteschlange",
    reconnecting: "Verbindung wird erneuert",
    cancelling: "Wird abgebrochen",
    cancelled: "Abgebrochen",
    failed: "Angehalten",
    incomplete: "Fortsetzung erforderlich",
    published: "Veröffentlicht",
    queuedDetail: "Warten auf freie Recherchekapazität.",
    reconnectingDetail: "Der aktuelle Serverstatus wird geprüft.",
    cancellingDetail: "Die Recherche wird sicher beendet.",
    cancelledDetail: "Die Recherche wurde abgebrochen.",
    failedDetail:
      "Die Recherche wurde angehalten. Fertige Arbeit bleibt gespeichert.",
    incompleteDetail: "Fertige Arbeit ist zur Fortsetzung gespeichert.",
    publishedDetail: "Der Recherchebericht wurde veröffentlicht.",
    done: "Abgeschlossen",
    current: "Aktuelle Phase",
    upcoming: "Ausstehend",
  },
  fr: {
    title: "Avancement de la recherche",
    prepare: "Préparation",
    investigate: "Recherche",
    discuss: "Revue en équipe",
    audit: "Vérification",
    publish: "Publication",
    prepareDetail: "Collecte et organisation des sources pour l’équipe.",
    investigateDetail:
      "Les agents examinent les éléments de manière indépendante.",
    discussDetail:
      "Les équipes comparent les résultats et évaluent les contre-arguments.",
    auditDetail: "Vérification des éléments et des sources des résultats.",
    publishDetail: "Le comité prépare le rapport en vue de sa publication.",
    working: "En cours",
    queued: "En attente",
    reconnecting: "Reconnexion",
    cancelling: "Annulation",
    cancelled: "Annulée",
    failed: "Interrompue",
    incomplete: "Reprise nécessaire",
    published: "Publié",
    queuedDetail: "En attente de capacité pour lancer la recherche.",
    reconnectingDetail: "Vérification du dernier état du serveur.",
    cancellingDetail: "Arrêt de la recherche en toute sécurité.",
    cancelledDetail: "La recherche a été annulée.",
    failedDetail:
      "La recherche est interrompue. Le travail terminé est conservé.",
    incompleteDetail:
      "Le travail terminé est conservé pour permettre la reprise.",
    publishedDetail: "Le rapport de recherche a été publié.",
    done: "Terminé",
    current: "Étape actuelle",
    upcoming: "À venir",
  },
} satisfies Record<AppLocale, Record<ProgressCopyKey, string>>;
