import type { ActorDefinition, Rect, SeatPlace, TeamTable } from "./types";

export const WORLD = { width: 1374, height: 1145 } as const;
export const ROSTER: readonly ActorDefinition[] = [
  {
    id: "market",
    name: "마야",
    role: "시장 분석",
    color: "#81b6cf",
    seat: { x: 185, y: 510 },
    homeFacing: "down",
    lead: true,
  },
  {
    id: "market_news",
    name: "준",
    role: "기술적 분석",
    color: "#81b6cf",
    seat: { x: 345, y: 510 },
    homeFacing: "down",
    lead: false,
  },
  {
    id: "benchmark",
    name: "알렉스",
    role: "시장 비교",
    color: "#81b6cf",
    seat: { x: 475, y: 510 },
    homeFacing: "down",
    lead: false,
  },
  {
    id: "company",
    name: "이든",
    role: "기업 분석",
    color: "#7ab4a7",
    seat: { x: 1035, y: 510 },
    homeFacing: "down",
    lead: true,
  },
  {
    id: "company_product",
    name: "아리아",
    role: "제품 분석",
    color: "#7ab4a7",
    seat: { x: 1170, y: 510 },
    homeFacing: "down",
    lead: false,
  },
  {
    id: "company_competition",
    name: "레오",
    role: "경쟁 분석",
    color: "#7ab4a7",
    seat: { x: 1290, y: 510 },
    homeFacing: "down",
    lead: false,
  },
  {
    id: "financial",
    name: "노아",
    role: "재무 분석",
    color: "#c8a778",
    seat: { x: 200, y: 1070 },
    homeFacing: "down",
    lead: true,
  },
  {
    id: "valuation",
    name: "소피아",
    role: "가치평가",
    color: "#c8a778",
    seat: { x: 375, y: 1070 },
    homeFacing: "down",
    lead: false,
  },
  {
    id: "financial_quality",
    name: "하나",
    role: "이익의 질",
    color: "#c8a778",
    seat: { x: 535, y: 1070 },
    homeFacing: "down",
    lead: false,
  },
  {
    id: "risk",
    name: "리암",
    role: "리스크 분석",
    color: "#b39ac7",
    seat: { x: 955, y: 1070 },
    homeFacing: "down",
    lead: true,
  },
  {
    id: "risk_policy",
    name: "민",
    role: "정책·시나리오",
    color: "#b39ac7",
    seat: { x: 1175, y: 1070 },
    homeFacing: "down",
    lead: false,
  },
  {
    id: "chair",
    name: "박 의장",
    role: "리서치 의장",
    color: "#e0bb78",
    seat: { x: 744, y: 302 },
    homeFacing: "down",
    lead: true,
  },
];

export const TEAM_TABLES: readonly TeamTable[] = [
  {
    id: "market",
    label: "시장팀 회의",
    color: "#81b6cf",
    center: { x: 340, y: 320 },
    radiusX: 90,
    radiusY: 32,
    seats: [
      { id: "market", position: { x: 230, y: 320 }, facing: "right" },
      { id: "market_news", position: { x: 340, y: 390 }, facing: "up" },
      { id: "benchmark", position: { x: 450, y: 320 }, facing: "left" },
    ],
  },
  {
    id: "company",
    label: "기업팀 회의",
    color: "#7ab4a7",
    center: { x: 1155, y: 320 },
    radiusX: 90,
    radiusY: 32,
    seats: [
      { id: "company", position: { x: 1045, y: 320 }, facing: "right" },
      { id: "company_product", position: { x: 1155, y: 390 }, facing: "up" },
      {
        id: "company_competition",
        position: { x: 1265, y: 320 },
        facing: "left",
      },
    ],
  },
  {
    id: "financial",
    label: "재무팀 회의",
    color: "#c8a778",
    center: { x: 360, y: 830 },
    radiusX: 90,
    radiusY: 32,
    seats: [
      { id: "financial", position: { x: 250, y: 830 }, facing: "right" },
      { id: "valuation", position: { x: 360, y: 900 }, facing: "up" },
      { id: "financial_quality", position: { x: 470, y: 830 }, facing: "left" },
    ],
  },
  {
    id: "risk",
    label: "리스크팀 회의",
    color: "#b39ac7",
    center: { x: 1125, y: 830 },
    radiusX: 90,
    radiusY: 32,
    seats: [
      { id: "risk", position: { x: 1015, y: 830 }, facing: "right" },
      { id: "risk_policy", position: { x: 1235, y: 830 }, facing: "left" },
    ],
  },
];

export const WALLS: readonly Rect[] = [
  { x: 548, y: 20, width: 28, height: 327 },
  { x: 548, y: 424, width: 28, height: 145 },
  { x: 914, y: 20, width: 30, height: 327 },
  { x: 914, y: 424, width: 30, height: 145 },
  { x: 16, y: 565, width: 616, height: 75 },
  { x: 714, y: 565, width: 643, height: 75 },
  { x: 614, y: 626, width: 27, height: 184 },
  { x: 614, y: 953, width: 27, height: 175 },
  { x: 714, y: 626, width: 28, height: 184 },
  { x: 714, y: 953, width: 28, height: 175 },
];

export const FORUM_PLACES: Readonly<
  Record<"market" | "company" | "financial" | "risk" | "chair", SeatPlace>
> = {
  market: { position: { x: 620, y: 457 }, facing: "right" },
  company: { position: { x: 868, y: 457 }, facing: "left" },
  financial: { position: { x: 686, y: 545 }, facing: "up" },
  risk: { position: { x: 802, y: 545 }, facing: "up" },
  chair: { position: { x: 744, y: 393 }, facing: "down" },
};
