import { workflowRoleById } from "../../../research/domain/roleRegistry";
import { publicDecisionDimensionLabel } from "../../../research/publicPresentation";
import {
  claimOwnedCheckpoint,
  type DepartmentReportBodyProps,
  departmentSectionCopy,
} from "./DepartmentReportShared";
import {
  FINANCIAL_BRIDGE_METRIC_IDS,
  formatFinancialMetric,
  selectAlignedFinancialPeriods,
  selectAuditableValuation,
  selectFinancialDiagnostics,
  selectFinancialExpectations,
} from "./FinancialReportModel";
import styles from "./financial-report.module.css";
import {
  ResearchFileSectionHeader,
  ResearchInlineHelp,
  ResearchTermHelp,
} from "./ResearchFilePrimitives";

function financialExpectationGroup(metricId: string) {
  if (metricId.startsWith("recommendation_")) return "positioning" as const;
  if (
    metricId.includes("price_target") ||
    metricId.includes("forward_pe") ||
    metricId.includes("valuation")
  )
    return "valuation" as const;
  return "earnings" as const;
}

function financialMetricDescription(metricId: string, locale: "ko" | "en") {
  const ko = locale === "ko";
  const id = metricId.toLowerCase();
  if (id.includes("gross_margin"))
    return ko
      ? "매출에서 제품·서비스를 직접 제공하는 원가를 뺀 비율입니다. 가격 결정력과 원가 구조를 함께 봅니다."
      : "Revenue left after direct costs, used to assess pricing power and cost structure.";
  if (id.includes("operating_margin"))
    return ko
      ? "매출에서 영업비용까지 뺀 뒤 남는 이익 비율입니다. 본업의 수익성과 비용 통제력을 보여줍니다."
      : "Profit left after operating expenses, indicating core profitability and cost control.";
  if (id.includes("free_cash_flow"))
    return ko
      ? "영업에서 번 현금에서 설비투자를 뺀 금액입니다. 부채 상환·자사주·배당에 실제로 쓸 수 있는 현금을 봅니다."
      : "Operating cash flow after capital expenditure, available for debt reduction and shareholder returns.";
  if (id.includes("operating_cash_flow"))
    return ko
      ? "본업이 실제로 만들어낸 현금입니다. 회계상 이익이 현금으로 전환되는지 확인합니다."
      : "Cash generated by core operations, used to test whether accounting profit converts into cash.";
  if (id.includes("net_income"))
    return ko
      ? "모든 비용·이자·세금을 반영한 최종 이익입니다. 일회성 요인의 영향도 함께 확인해야 합니다."
      : "Profit after all expenses, interest, and tax; one-off effects should be checked separately.";
  if (id.includes("capex"))
    return ko
      ? "설비·인프라 등 장기 자산에 투입한 현금입니다. 성장 투자와 현금 소모의 균형을 봅니다."
      : "Cash invested in long-lived assets, showing the balance between growth investment and cash use.";
  if (id.includes("revenue"))
    return ko
      ? "기업이 제품과 서비스 판매로 벌어들인 총매출입니다. 성장의 규모와 방향을 판단하는 출발점입니다."
      : "Total sales from products and services, the starting point for assessing growth.";
  return ko
    ? "이 지표가 이익의 질과 현금 창출력에 어떤 영향을 주는지 확인합니다."
    : "Use this metric to assess earnings quality and cash-generation capacity.";
}

function Sparkline({ values }: { readonly values: readonly number[] }) {
  const minimum = Math.min(...values);
  const maximum = Math.max(...values);
  const range = maximum - minimum || 1;
  const points = values
    .map((value, index) => {
      const x = values.length === 1 ? 50 : (index / (values.length - 1)) * 100;
      const y = 28 - ((value - minimum) / range) * 24;
      return `${x},${y}`;
    })
    .join(" ");
  return (
    <svg viewBox="0 0 100 32" role="img" aria-label="Historical trend">
      <polyline points={points} fill="none" vectorEffect="non-scaling-stroke" />
    </svg>
  );
}

export function FinancialReportBrief({
  file,
  model,
  locale,
}: DepartmentReportBodyProps) {
  const ko = locale === "ko";
  const copy = departmentSectionCopy("financial", locale);
  const periods = selectAlignedFinancialPeriods(file);
  const diagnostics = selectFinancialDiagnostics(file);
  const snapshot = (file.metricSnapshot?.metrics ?? [])
    .filter((metric) => metric.category === "financial")
    .slice(0, 6);
  const financialClaims = (model.structuredClaims ?? []).filter(
    (claim) => workflowRoleById(claim.roleOwner)?.departmentId === "financial",
  );
  return (
    <section
      className="research-editorial-section research-department-section"
      data-report-section="decision"
      data-department-layout="financial"
      id="decision-brief"
    >
      <ResearchFileSectionHeader
        number="01"
        title={copy.primaryTitle}
        description={copy.primaryDescription}
        help={{ term: "financialLab", locale }}
      />
      {diagnostics.length === 0 ? null : (
        <section
          className={styles["diagnostics"]}
          data-financial-diagnostics={diagnostics.length}
        >
          {diagnostics.map((diagnostic) => (
            <article
              key={diagnostic.id}
              data-source-ids={diagnostic.sourceIds.join(",")}
            >
              <ResearchInlineHelp
                label={diagnostic.label[locale]}
                description={diagnostic.interpretation[locale]}
                locale={locale}
              />
              <strong>{diagnostic.value.toFixed(1)}%</strong>
              <p>{diagnostic.interpretation[locale]}</p>
            </article>
          ))}
        </section>
      )}
      {periods.length === 0 ? (
        <section
          className={styles["snapshot"]}
          data-financial-snapshot="current"
        >
          {snapshot.map((metric) => (
            <article key={metric.id}>
              <ResearchInlineHelp
                label={metric.label[locale]}
                description={financialMetricDescription(metric.id, locale)}
                locale={locale}
              />
              <strong>{formatFinancialMetric(metric, locale)}</strong>
              <small>{metric.period ?? metric.observedAt.slice(0, 10)}</small>
            </article>
          ))}
          {snapshot.length === 0
            ? financialClaims.slice(0, 3).map((claim) => (
                <article
                  key={claim.claimId}
                  className={styles["snapshotClaim"]}
                >
                  <span>
                    {publicDecisionDimensionLabel(
                      claim.decisionDimension,
                      locale,
                    )}
                  </span>
                  <p>{claim.publicThesis[locale]}</p>
                </article>
              ))
            : null}
        </section>
      ) : (
        <section
          className={styles["bridge"]}
          data-financial-bridge="period-aligned"
          data-financial-metric-ids={FINANCIAL_BRIDGE_METRIC_IDS.join(",")}
          aria-labelledby="financial-bridge-title"
        >
          <header>
            <div>
              <span>
                {ko
                  ? "기간 정렬 손익·현금 브리지"
                  : "Period-aligned earnings & cash bridge"}
              </span>
              <h3 id="financial-bridge-title">
                {ko
                  ? "매출이 마진을 거쳐 현금과 재투자로 전환되는가"
                  : "Does revenue convert through margins into cash and reinvestment?"}
              </h3>
            </div>
            <small>{file.metricSnapshot?.asOf.slice(0, 10)}</small>
          </header>
          <section
            className={styles["trends"]}
            aria-label={ko ? "역사적 추세" : "Historical trends"}
          >
            {FINANCIAL_BRIDGE_METRIC_IDS.map((metricId) => {
              const metric = periods.at(-1)?.metrics[metricId];
              if (metric === undefined) return null;
              const first = periods[0]?.metrics[metricId];
              const delta =
                first === undefined ? 0 : metric.value - first.value;
              const deltaLabel =
                metric.unit === "percent"
                  ? `${delta >= 0 ? "+" : ""}${delta.toFixed(1)}%p`
                  : first === undefined || first.value === 0
                    ? "—"
                    : `${((delta / Math.abs(first.value)) * 100) >= 0 ? "+" : ""}${((delta / Math.abs(first.value)) * 100).toFixed(1)}%`;
              return (
                <figure key={metricId} data-financial-trend={metricId}>
                  <figcaption>
                    <ResearchInlineHelp
                      label={metric.label[locale]}
                      description={financialMetricDescription(
                        metric.id,
                        locale,
                      )}
                      locale={locale}
                    />
                    <strong>{formatFinancialMetric(metric, locale)}</strong>
                    <em data-direction={delta >= 0 ? "up" : "down"}>
                      {deltaLabel}
                    </em>
                  </figcaption>
                  <Sparkline
                    values={periods.map(
                      (period) => period.metrics[metricId].value,
                    )}
                  />
                </figure>
              );
            })}
          </section>
          <div className={styles["tableWrap"]}>
            <table>
              <thead>
                <tr>
                  <th>{ko ? "기간" : "Period"}</th>
                  {FINANCIAL_BRIDGE_METRIC_IDS.map((metricId) => (
                    <th key={metricId}>
                      {periods[0]?.metrics[metricId].label[locale]}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {periods.map((period) => (
                  <tr key={period.period} data-financial-period={period.period}>
                    <th>{period.period}</th>
                    {FINANCIAL_BRIDGE_METRIC_IDS.map((metricId) => {
                      const metric = period.metrics[metricId];
                      return (
                        <td
                          key={metricId}
                          data-metric-id={metric.id}
                          data-metric-source={metric.source}
                        >
                          {formatFinancialMetric(metric, locale)}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}
    </section>
  );
}

export function FinancialReportFramework({
  file,
  model,
  locale,
}: DepartmentReportBodyProps) {
  const ko = locale === "ko";
  const copy = departmentSectionCopy("financial", locale);
  const expectations = selectFinancialExpectations(file);
  const valuation = selectAuditableValuation(model.comparatorQualification);
  const checkpoint = claimOwnedCheckpoint(model, "financial", locale);
  const structuredTests = (model.structuredClaims ?? []).filter(
    (claim) => workflowRoleById(claim.roleOwner)?.departmentId === "financial",
  );
  const claimTests =
    structuredTests.length > 0
      ? structuredTests.map((claim) => ({
          id: claim.claimId,
          thesis: claim.publicThesis[locale],
          falsifier: claim.falsifier[locale],
        }))
      : model.analysisRows.slice(0, 3).map((row) => ({
          id: row.id,
          thesis: row.evidence,
          falsifier: row.checkpoint,
        }));
  const expectationGroups = [
    {
      id: "earnings" as const,
      label: ko ? "실적 기대" : "Earnings expectations",
      description: ko
        ? "다음 실적에 반영된 매출·EPS 추정"
        : "Forward revenue and EPS estimates",
    },
    {
      id: "valuation" as const,
      label: ko ? "가격 기대" : "Valuation expectations",
      description: ko
        ? "목표주가와 선행 배수"
        : "Price targets and forward multiples",
    },
    {
      id: "positioning" as const,
      label: ko ? "의견 분포" : "Recommendation mix",
      description: ko ? "매수·중립·매도 집계" : "Buy, hold, and sell counts",
    },
  ]
    .map((group) => ({
      ...group,
      metrics: expectations.filter(
        (metric) => financialExpectationGroup(metric.id) === group.id,
      ),
    }))
    .filter((group) => group.metrics.length > 0);
  return (
    <section
      className="research-editorial-section research-department-section"
      data-report-section="expectations"
      data-department-layout="financial"
      id="decision-scenarios"
    >
      <ResearchFileSectionHeader
        number="02"
        title={copy.secondaryTitle}
        description={copy.secondaryDescription}
      />
      {expectations.length === 0 ? null : (
        <section
          className={styles["expectations"]}
          aria-labelledby="expectations-title"
        >
          <h3
            id="expectations-title"
            aria-label={
              ko
                ? "관측된 내재 기대 입력"
                : "Observed embedded-expectation inputs"
            }
          >
            <ResearchTermHelp
              term="embeddedExpectations"
              label={
                ko
                  ? "관측된 내재 기대 입력"
                  : "Observed implied-expectation inputs"
              }
              locale={locale}
            />
          </h3>
          <div
            className={styles["expectationGroups"]}
            data-group-count={expectationGroups.length}
          >
            {expectationGroups.map((group) => (
              <section key={group.id} data-expectation-group={group.id}>
                <header>
                  <strong>{group.label}</strong>
                  <span>{group.description}</span>
                </header>
                <dl>
                  {group.metrics.map((metric) => (
                    <div
                      key={`${metric.id}:${metric.period ?? metric.observedAt}`}
                      data-expectation-metric-id={metric.id}
                      data-metric-source={metric.source}
                    >
                      <dt>
                        <span>{metric.label[locale]}</span>
                        <small>
                          {metric.period ?? metric.observedAt.slice(0, 10)}
                        </small>
                      </dt>
                      <dd>{formatFinancialMetric(metric, locale)}</dd>
                    </div>
                  ))}
                </dl>
              </section>
            ))}
          </div>
        </section>
      )}
      {claimTests.length === 0 ? null : (
        <section
          className={styles["claimTests"]}
          data-financial-expectation-tests="claims"
        >
          <h3>
            {ko
              ? "현재 가격을 검증할 운영 질문"
              : "Operating tests for the current price"}
          </h3>
          <ol>
            {claimTests.slice(0, 6).map((claim, index) => (
              <li key={claim.id}>
                <span>TEST {String(index + 1).padStart(2, "0")}</span>
                <div>
                  <strong>{claim.thesis}</strong>
                  {claim.falsifier.trim() === claim.thesis.trim() ? null : (
                    <p>{claim.falsifier}</p>
                  )}
                </div>
              </li>
            ))}
          </ol>
        </section>
      )}
      {valuation === undefined ? null : (
        <section
          className={styles["valuation"]}
          data-valuation-comparison={valuation.metricKey}
          data-valuation-evidence-ids={valuation.evidenceArtifactIds.join(",")}
          aria-labelledby="valuation-comparison-title"
        >
          <header>
            <h3
              id="valuation-comparison-title"
              aria-label={
                ko ? "검증된 상대 가치평가" : "Qualified relative valuation"
              }
            >
              <ResearchTermHelp
                term="relativeValuation"
                label={
                  ko ? "검증된 상대 가치평가" : "Qualified relative valuation"
                }
                locale={locale}
              />
            </h3>
            <span>{valuation.period}</span>
          </header>
          <div className={styles["valuationSummary"]}>
            <div>
              <span>{ko ? "대상" : "Subject"}</span>
              <strong>{valuation.subjectValue.toFixed(1)}×</strong>
            </div>
            <div>
              <span>{ko ? "동종 중앙값" : "Peer median"}</span>
              <strong>{valuation.peerMedian.toFixed(1)}×</strong>
            </div>
            <div>
              <span>{ko ? "프리미엄·할인" : "Premium / discount"}</span>
              <strong>{valuation.premiumDiscountPercent.toFixed(1)}%</strong>
            </div>
          </div>
          <ul>
            {valuation.peers.map((peer) => (
              <li
                key={peer.comparatorId}
                data-comparator-id={peer.comparatorId}
                data-evidence-ids={peer.evidenceArtifactIds.join(",")}
              >
                <span>{peer.name}</span>
                <strong>{peer.value.toFixed(1)}×</strong>
              </li>
            ))}
          </ul>
        </section>
      )}
      {checkpoint === undefined ? null : (
        <aside
          className={styles["checkpoint"]}
          data-financial-checkpoint="claim-owned"
        >
          <span>{ko ? "검증 조건" : "Verification condition"}</span>
          <p>{checkpoint}</p>
        </aside>
      )}
    </section>
  );
}
