import type { WorkflowRole } from "./roleRegistry";

export const WORKFLOW_V1_ROLES = [
  {
    id: "market",
    name: "Maya",
    departmentId: "market",
    isDepartmentLead: true,
    evidenceNeeds: [
      "issuer_identity",
      "sec_primary_filings",
      "sec_company_facts",
      "bls_cpi",
      "bls_core_cpi",
      "bls_unemployment",
      "bls_nonfarm_payrolls",
      "bls_average_hourly_earnings",
      "bls_producer_prices",
      "treasury_yield_curve",
      "sec_beneficial_ownership",
      "categorized_news_events",
      "capability_posture",
      "question_mandate",
    ],
  },
  {
    id: "market_news",
    name: "June",
    departmentId: "market",
    isDepartmentLead: false,
    evidenceNeeds: [
      "provider_technical_1h",
      "provider_technical_4h",
      "categorized_news_events",
      "observed_provider_coverage",
      "capability_posture",
      "question_mandate",
    ],
  },
  {
    id: "benchmark",
    name: "Alex",
    departmentId: "market",
    isDepartmentLead: false,
    evidenceNeeds: [
      "provider_peer_context",
      "provider_fundamentals",
      "provider_technical_1h",
      "provider_technical_4h",
      "treasury_yield_curve",
      "categorized_news_events",
      "observed_provider_coverage",
      "capability_posture",
      "question_mandate",
    ],
  },
  {
    id: "company",
    name: "Ethan",
    departmentId: "company",
    isDepartmentLead: true,
    evidenceNeeds: [
      "issuer_identity",
      "sec_primary_filings",
      "sec_current_reports",
      "sec_amendment_lineage",
      "sec_insider_transactions",
      "sec_beneficial_ownership",
      "categorized_news_events",
      "question_mandate",
    ],
  },
  {
    id: "company_product",
    name: "Aria",
    departmentId: "company",
    isDepartmentLead: false,
    evidenceNeeds: [
      "sec_primary_filings",
      "sec_current_reports",
      "categorized_news_events",
      "question_mandate",
    ],
  },
  {
    id: "company_competition",
    name: "Leo",
    departmentId: "company",
    isDepartmentLead: false,
    evidenceNeeds: [
      "sec_primary_filings",
      "sec_current_reports",
      "capability_posture",
      "question_mandate",
    ],
  },
  {
    id: "financial",
    name: "Noah",
    departmentId: "financial",
    isDepartmentLead: true,
    evidenceNeeds: [
      "sec_primary_filings",
      "sec_company_facts",
      "sec_amendment_lineage",
      "sec_insider_transactions",
      "sec_beneficial_ownership",
      "categorized_news_events",
      "question_mandate",
    ],
  },
  {
    id: "valuation",
    name: "Sofia",
    departmentId: "financial",
    isDepartmentLead: false,
    evidenceNeeds: [
      "sec_company_facts",
      "sec_primary_filings",
      "provider_fundamentals",
      "categorized_news_events",
      "observed_provider_coverage",
      "capability_posture",
      "question_mandate",
    ],
  },
  {
    id: "financial_quality",
    name: "Hana",
    departmentId: "financial",
    isDepartmentLead: false,
    evidenceNeeds: [
      "sec_primary_filings",
      "sec_company_facts",
      "sec_amendment_lineage",
      "categorized_news_events",
      "question_mandate",
    ],
  },
  {
    id: "risk",
    name: "Liam",
    departmentId: "risk",
    isDepartmentLead: true,
    evidenceNeeds: [
      "sec_primary_filings",
      "sec_current_reports",
      "sec_amendment_lineage",
      "bls_cpi",
      "bls_core_cpi",
      "bls_unemployment",
      "bls_nonfarm_payrolls",
      "bls_average_hourly_earnings",
      "bls_producer_prices",
      "treasury_yield_curve",
      "sec_insider_transactions",
      "sec_beneficial_ownership",
      "categorized_news_events",
      "question_mandate",
    ],
  },
  {
    id: "risk_policy",
    name: "Min",
    departmentId: "risk",
    isDepartmentLead: false,
    evidenceNeeds: [
      "sec_primary_filings",
      "sec_current_reports",
      "bls_cpi",
      "bls_core_cpi",
      "bls_unemployment",
      "bls_nonfarm_payrolls",
      "bls_average_hourly_earnings",
      "bls_producer_prices",
      "treasury_yield_curve",
      "sec_beneficial_ownership",
      "question_mandate",
    ],
  },
  {
    id: "chair",
    name: "Dr. Park",
    departmentId: "chair",
    isDepartmentLead: false,
    evidenceNeeds: [
      "accepted_agent_artifacts",
      "audited_claim_register",
      "department_ballots",
      "capability_posture",
      "question_mandate",
    ],
  },
] as const satisfies readonly WorkflowRole[];
