declare const styles: {
  readonly page: string;
  readonly chapter: string;
  readonly eyebrow: string;
  readonly thesis: string;
  readonly grid: string;
  readonly card: string;
  readonly expanded: string;
  readonly cardHeader: string;
  readonly cardMeta: string;
  readonly toolbar: string;
  readonly unavailable: string;
  readonly gestureHint: string;
  readonly canvas: string;
  readonly cardCopy: string;
  readonly observation: string;
  readonly levels: string;
  readonly drawingReason: string;
  readonly scenarios: string;
  readonly coverage: string;
  readonly footer: string;
};
export default styles;
