import type { EditorialLocaleContent } from "../types";
import { editorialEntry as e } from "./entry";

export const deEditorialContent = {
  ui: {
    blogEyebrow: "DAS RESEARCH-NOTIZBUCH",
    blogTitle: "US-Aktienanalyse, konsequent evidenzbasiert",
    blogDescription:
      "Praxisnahe Leitfäden zum Lesen von Berichten, Prüfen von Annahmen und Vergleichen von Unternehmen.",
    glossaryEyebrow: "ANLEGERGLOSSAR",
    glossaryTitle: "Finanzbegriffe als echte Analysewerkzeuge",
    glossaryDescription:
      "Klare Definitionen, Grenzen und typische Fehler für fundierteres Research.",
    backToBlog: "Zurück zum Blog",
    backToGlossary: "Zurück zum Glossar",
    readArticle: "Artikel lesen",
    readDefinition: "Definition lesen",
    readNext: "Als Nächstes",
    minutes: "Min. Lesezeit",
    updated: "Aktualisiert",
    ctaTitle: "Wende den Rahmen auf ein echtes Unternehmen an",
    ctaDescription:
      "Das Stocksembly-Team untersucht das Unternehmen, fordert die These heraus und sichert die Belege in einer Research-Datei.",
    ctaAction: "Aktienresearch starten",
    sidebarBlog: "Blog",
    sidebarGlossary: "Glossar",
  },
  entries: {
    "how-to-read-a-10-k": e(
      "So liest du einen 10-K für die Aktienanalyse",
      "Ein wiederholbarer Weg vom Geschäftsmodell über Cashflow und Risiken bis zu den nächsten Research-Fragen.",
      "BERICHTE",
      "Dunkler Jahresbericht mit blauen Evidenzmarkern auf einem Analystenschreibtisch",
      "Beginne mit dem Geschäft",
      "Erkläre anhand von Item 1, wer bezahlt, was gekauft wird und was für wiederkehrenden Umsatz gelten muss. Segmente, Kundenkonzentration, Vertrieb und Saisonalität zeigen oft die Lücke zwischen Erzählung und ökonomischem Motor.",
      "Gleiche Gewinn und Cashflow ab",
      "Verbinde operatives Ergebnis, operativen Cashflow und freien Cashflow. Prüfe temporäres Working Capital, aktivierte Kosten, Aktienvergütung und jährlich wiederkehrende Bereinigungen.",
      "Mache Risiken beobachtbar",
      "Bestimme das veränderte Risiko, den stärksten möglichen Thesenschaden und das früheste Warnsignal. Halte Fragen für Calls und Wettbewerberberichte fest.",
    ),
    "earnings-quality-and-cash-conversion": e(
      "Ergebnisqualität: Cash Conversion richtig prüfen",
      "Working Capital, Investitionsbedarf und wiederkehrende Anpassungen verändern das Bild des ausgewiesenen Gewinns.",
      "FINANZEN",
      "Transparenter Cashflow durch eine dunkle Betriebsmaschine",
      "Definiere den zu prüfenden Gewinn",
      "Nettoergebnis, operatives Ergebnis, EBITDA und bereinigter Gewinn beantworten verschiedene Fragen. Wähle die passende Größe und gleiche sie über einen Geschäftszyklus mit Cash ab.",
      "Klassifiziere die Abweichung",
      "Trenne wachstumsbedingte Forderungen und Vorräte, Vorauszahlungen, aktivierte Entwicklung, Aktienvergütung und Akquisitionen. Prüfe, ob Cash durch bessere Abläufe oder weniger Investitionen stieg.",
      "Beurteile die Haltbarkeit",
      "Nenne eine normalisierte Conversion und die Bilanzveränderung, die diese Einschätzung widerlegen würde.",
    ),
    "how-to-choose-comparable-companies": e(
      "So wählst du wirklich vergleichbare Unternehmen",
      "Peer-Auswahl beginnt beim Geschäftsmodell, nicht bei einer Multiplikatorentabelle.",
      "BEWERTUNG",
      "Fünf vermessene Unternehmensblöcke aus Glas, einer deutlich abweichend",
      "Vergleiche den ökonomischen Motor",
      "Untersuche Kundengewinnung, Preisbildung, Umsatzrealisierung, Wachstumsfinanzierung und Bindung. Ähnliche Umsätze bedeuten nicht ähnliche Ökonomie.",
      "Kontrolliere Reife und Kapitalbedarf",
      "Bilde eine Kerngruppe mit ähnlichem Wachstum, Margen, Reinvestitionen, Zyklik und Finanzrisiko; weitere Peers dienen nur als gezielte Referenz.",
      "Nutze das Multiple als Ergebnis",
      "Das Peer-Multiple zeigt Markterwartungen. Prüfe, ob die operative Historie die Position des Unternehmens trägt.",
    ),
    "bull-base-bear-scenario-analysis": e(
      "Leitfaden für Bull-, Base- und Bear-Szenarien",
      "Baue Szenarien aus konsistenten operativen Annahmen statt aus willkürlichen Kurszielen.",
      "SZENARIEN",
      "Ein blauer Analysepfad teilt sich in drei Marktszenarien",
      "Nutze ein gemeinsames Modell",
      "Verändere in jedem Fall dieselben Treiber: Volumen, Preis, Bindung, Bruttomarge, Investitionen und Kapital. Der Base Case ist der bestbelegte Pfad, nicht der mechanische Mittelwert.",
      "Erkläre den Mechanismus",
      "Verknüpfe jede Annahme mit einem auslösenden Ereignis und beobachtbarer Evidenz. Kombiniere nicht maximales Wachstum, maximale Marge und minimale Investition ohne Geschäftslogik.",
      "Definiere Updates",
      "Notiere das nächste wesentliche Ereignis, Frühwarnsignal und die gegenüber neuen Belegen sensibelste Annahme.",
    ),
    "counterarguments-in-ai-stock-research": e(
      "Warum KI-Aktienresearch ein starkes Gegenargument braucht",
      "Mehr Agenten garantieren keine bessere Analyse: Nötig sind unabhängige Prüfung und eine sichtbare Evidenzspur.",
      "PROZESS",
      "Zwei gegenüberliegende Research-Tische, verbunden durch einen blauen Evidenzstrahl",
      "Konsens kann scheitern",
      "Mehrere Modelle können dieselbe versteckte Annahme teilen. Wiederholtes Fragen erhöht dann Selbstvertrauen ohne unabhängige Belege; trenne Rollen, Quellen und Kriterien.",
      "Mache die Gegenthese falsifizierbar",
      "Der Challenger nennt die stärkste Alternative, ihre Evidenz und die Beobachtung, die sie widerlegt, und prüft Aktualität, Rechnungslegung, Basisraten und Kausalität.",
      "Veröffentliche die Debatte",
      "Entfernte Aussagen, offene Fragen und die finale Begründung machen spätere Revisionen auditierbar.",
    ),
    "free-cash-flow": e(
      "Free Cashflow (FCF)",
      "Cash, der nach den nötigen Investitionen für Erhalt und Wachstum des Geschäfts verbleibt.",
      "CASHFLOW",
      "Blauer Cash-Strom fließt durch einen Investitionsfilter",
      "Definition",
      "Üblich ist operativer Cashflow minus Investitionsausgaben. Die Kennzahl nähert den Spielraum für Schulden, Zukäufe, Rückkäufe, Dividenden oder Reinvestitionen an.",
      "Typische Falle",
      "FCF kann durch verschobene Investitionen oder freigesetztes Working Capital steigen. Aktienvergütung, Leasing, wiederkehrende Zukäufe und aktivierte Entwicklung gehören in den Abgleich.",
    ),
    "ev-to-ebitda": e(
      "EV/EBITDA",
      "Bewertungsmultiple aus Unternehmenswert und Ergebnis vor Zinsen, Steuern und Abschreibungen.",
      "BEWERTUNG",
      "Unternehmensstruktur balanciert über einem operativen Motor",
      "Definition",
      "Der Enterprise Value verbindet Eigenkapitalwert, Schulden und Cash, um operative Unternehmen mit unterschiedlicher Finanzierung zu vergleichen.",
      "Typische Falle",
      "EBITDA ignoriert Investitionen und Working Capital und kann kapitalintensive oder akquisitive Unternehmen zu günstig erscheinen lassen. Mit FCF kombinieren.",
    ),
    "earnings-guidance": e(
      "Ergebnisprognose (Guidance)",
      "Bandbreite oder qualitative Einschätzung des Managements zu künftigem Umsatz, Gewinn, Margen oder Kennzahlen.",
      "ERWARTUNGEN",
      "Dunkle Quartalsbahn führt zu einem blauen Ausblicksignal",
      "Definition",
      "Guidance überführt aktuelle Informationen in eine Bandbreite für Quartal oder Jahr und kann Umsatz, bereinigten Gewinn, Marge, Investitionen oder Branchen-KPIs enthalten.",
      "Analyse",
      "Vergleiche Mittelpunkt, Breite, Annahmen und Ausschlüsse mit früherer Guidance und Ergebnissen. Trenne veränderten Geschäftsausblick von geänderter Definition.",
    ),
    "share-dilution": e(
      "Aktienverwässerung",
      "Sinkender Anteil bestehender Eigentümer, wenn die effektive Aktienzahl steigt.",
      "EIGENTUM",
      "Blauer Eigentumsring wird in viele Segmente geteilt",
      "Definition",
      "Neue Aktien, Optionen, Restricted Shares und Wandelinstrumente erhöhen Ansprüche auf den Unternehmenswert; Gesamtwert und Wert je Aktie können unterschiedlich wachsen.",
      "Messung",
      "Verfolge verwässerte Durchschnitts- und Stichtagsaktien, Vergütung und Wandelinstrumente. Vergleiche Gesamt- mit Pro-Aktie-Wachstum und die realen Rückkaufkosten.",
    ),
    "margin-of-safety": e(
      "Sicherheitsmarge",
      "Puffer zwischen konservativ geschätztem Wert und gezahltem Preis, der Unsicherheit und Fehler auffängt.",
      "RISIKO",
      "Blaue Bewertungsbrücke über einer volatilen Marktfläche",
      "Definition",
      "Sie ist kein fixer Abschlag. Je unsicherer Nachfrage, Margen, Finanzierung, Wettbewerbsvorteil und Bewertung, desto größer sollte der Puffer meist sein.",
      "Typische Falle",
      "Ein Kursrückgang vom Hoch oder ein niedriges Multiple schaffen keine Sicherheitsmarge. Vergleiche mit einer evidenzbasierten, anpassbaren Wertspanne.",
    ),
  },
} satisfies EditorialLocaleContent;
