import type { EditorialLocaleContent } from "../types";
import { editorialEntry as e } from "./entry";

export const esEditorialContent = {
  ui: {
    blogEyebrow: "CUADERNO DE ANÁLISIS",
    blogTitle: "Análisis de acciones de EE. UU., con evidencia",
    blogDescription:
      "Guías prácticas para leer reportes, probar supuestos y comparar empresas.",
    glossaryEyebrow: "GLOSARIO DEL INVERSOR",
    glossaryTitle: "Términos financieros que sí puedes usar",
    glossaryDescription:
      "Definiciones claras, límites y errores frecuentes para investigar mejor.",
    backToBlog: "Volver al blog",
    backToGlossary: "Volver al glosario",
    readArticle: "Leer artículo",
    readDefinition: "Ver definición",
    readNext: "Sigue leyendo",
    minutes: "min de lectura",
    updated: "Actualizado",
    ctaTitle: "Aplica el marco a una empresa real",
    ctaDescription:
      "El equipo de Stocksembly investiga la empresa, desafía la tesis y conserva la evidencia en un solo archivo.",
    ctaAction: "Iniciar análisis",
    sidebarBlog: "Blog",
    sidebarGlossary: "Glosario",
  },
  entries: {
    "how-to-read-a-10-k": e(
      "Cómo leer un 10-K para analizar acciones",
      "Un proceso repetible para pasar del modelo de negocio al efectivo, los riesgos y las preguntas pendientes.",
      "REPORTES",
      "Reporte anual oscuro con pestañas azules sobre un escritorio de análisis",
      "Empieza por el negocio",
      "Lee el Item 1 y explica quién paga, qué compra y qué debe mantenerse para que los ingresos se repitan. Separa segmentos, concentración de clientes, canales y estacionalidad; ahí suele aparecer la diferencia entre el relato comercial y el motor económico.",
      "Concilia la narrativa con el efectivo",
      "Conecta utilidad operativa, flujo operativo y flujo de caja libre. Revisa capital de trabajo temporal, costos capitalizados, compensación en acciones y ajustes que reaparecen cada año.",
      "Convierte riesgos en señales",
      "Identifica qué riesgo cambió, cuál dañaría más la tesis y qué dato avisaría primero. Termina con preguntas para la llamada de resultados y los reportes de competidores.",
    ),
    "earnings-quality-and-cash-conversion": e(
      "Calidad de ganancias: cómo probar la conversión a efectivo",
      "El capital de trabajo, la inversión y los ajustes recurrentes pueden cambiar por completo la utilidad reportada.",
      "FINANZAS",
      "Flujo de efectivo transparente atravesando un motor operativo oscuro",
      "Define qué ganancia validarás",
      "Utilidad neta, operativa, EBITDA y utilidad ajustada responden preguntas distintas. Elige la medida adecuada y concíliala con efectivo durante un ciclo, no solo un trimestre.",
      "Clasifica la diferencia",
      "Distingue cuentas por cobrar e inventario por crecimiento, cobros anticipados, desarrollo capitalizado, compensación accionaria y adquisiciones. Verifica si el efectivo mejoró por operación o por menor inversión.",
      "Concluye sobre durabilidad",
      "Estima una conversión normal y señala qué movimiento del balance invalidaría esa lectura.",
    ),
    "how-to-choose-comparable-companies": e(
      "Cómo elegir empresas comparables de verdad",
      "La selección de pares comienza con el modelo de negocio, no con una tabla de múltiplos.",
      "VALUACIÓN",
      "Cinco bloques empresariales de vidrio medidos, uno claramente distinto",
      "Compara el motor económico",
      "Evalúa adquisición de clientes, precios, reconocimiento de ingresos, financiación del crecimiento y retención. Ingresos parecidos no garantizan economías parecidas.",
      "Ajusta madurez y capital",
      "Forma un grupo central con crecimiento, márgenes, reinversión, ciclicidad y riesgo financiero similares; usa otros pares solo como referencia de una dimensión.",
      "Trata el múltiplo como resultado",
      "El múltiplo muestra expectativas del mercado. Comprueba si el historial operativo de la empresa justifica esa posición.",
    ),
    "bull-base-bear-scenario-analysis": e(
      "Guía de escenarios alcista, base y bajista",
      "Construye escenarios con supuestos operativos coherentes, no con precios objetivo arbitrarios.",
      "ESCENARIOS",
      "Un camino analítico azul que se divide en tres escenarios",
      "Usa un modelo común",
      "Cambia las mismas variables: volumen, precio, retención, margen bruto, inversión y capital. El caso base debe ser el camino mejor sustentado, no un promedio mecánico.",
      "Explica el mecanismo",
      "Vincula cada supuesto con un evento y una evidencia observable. No combines máximo crecimiento, máximo margen y mínima inversión sin una lógica empresarial que lo permita.",
      "Define cuándo actualizar",
      "Registra el próximo evento material, la señal temprana y el supuesto más sensible a nueva evidencia.",
    ),
    "counterarguments-in-ai-stock-research": e(
      "Por qué la investigación con IA necesita un contraargumento fuerte",
      "Más agentes no garantizan mejor análisis: hacen falta desafío independiente y una huella de evidencia.",
      "PROCESO",
      "Dos mesas de investigación opuestas unidas por un haz azul de evidencia",
      "El consenso puede fallar",
      "Varios modelos pueden compartir el mismo supuesto oculto. Repetir una pregunta aumenta la confianza sin añadir evidencia independiente; primero separa funciones, fuentes y criterios.",
      "Haz falsable la alternativa",
      "El crítico debe presentar la mejor explicación rival, su evidencia y la observación que la refutaría, además de revisar actualidad, definiciones contables y causalidad.",
      "Publica el desacuerdo",
      "Conservar afirmaciones eliminadas, dudas abiertas y la razón final permite auditar futuras revisiones.",
    ),
    "free-cash-flow": e(
      "Flujo de caja libre (FCF)",
      "Efectivo que queda después de la inversión necesaria para mantener y hacer crecer el negocio.",
      "EFECTIVO",
      "Flujo azul de efectivo atravesando un filtro de inversión",
      "Definición",
      "Suele calcularse como flujo operativo menos gasto de capital y aproxima el efectivo disponible para deuda, adquisiciones, recompras, dividendos o reinversión.",
      "Error frecuente",
      "Puede subir por aplazar inversión o liberar capital de trabajo. Concilia también acciones, arrendamientos, adquisiciones repetidas y desarrollo capitalizado.",
    ),
    "ev-to-ebitda": e(
      "EV/EBITDA",
      "Múltiplo que compara el valor empresarial con el beneficio antes de intereses, impuestos, depreciación y amortización.",
      "VALUACIÓN",
      "Estructura empresarial equilibrada sobre un motor operativo",
      "Definición",
      "El valor empresarial combina capitalización, deuda y efectivo para comparar negocios con estructuras de financiación diferentes.",
      "Error frecuente",
      "EBITDA omite inversión y capital de trabajo, por lo que puede abaratar artificialmente negocios intensivos en activos o adquisiciones. Úsalo con FCF.",
    ),
    "earnings-guidance": e(
      "Guía de resultados",
      "Rango o perspectiva cualitativa de la dirección sobre ingresos, beneficios, márgenes u otras métricas futuras.",
      "EXPECTATIVAS",
      "Pista trimestral oscura que conduce a una señal azul",
      "Definición",
      "La guía transforma información actual en un rango para el próximo trimestre o año y puede incluir ingresos, utilidad ajustada, margen, inversión o KPI sectoriales.",
      "Cómo analizarla",
      "Compara punto medio, amplitud, supuestos y exclusiones con guías anteriores y resultados reales. Separa un cambio del negocio de un cambio de definición.",
    ),
    "share-dilution": e(
      "Dilución accionaria",
      "Reducción del porcentaje de propiedad existente cuando aumenta el número efectivo de acciones.",
      "PROPIEDAD",
      "Anillo azul de propiedad dividido en muchos segmentos",
      "Definición",
      "Nuevas acciones, opciones, unidades restringidas y convertibles aumentan los derechos sobre el valor; el valor total puede crecer más rápido que el valor por acción.",
      "Cómo medirla",
      "Sigue acciones diluidas promedio y al cierre, compensación y convertibles. Compara crecimiento total con crecimiento por acción y el costo real de las recompras.",
    ),
    "margin-of-safety": e(
      "Margen de seguridad",
      "Colchón entre una estimación conservadora de valor y el precio pagado para absorber incertidumbre y errores.",
      "RIESGO",
      "Puente azul de valoración sobre una superficie de mercado volátil",
      "Definición",
      "No es un descuento fijo. Cuanta más incertidumbre exista en demanda, márgenes, financiación, ventaja competitiva y valoración, mayor suele ser el colchón necesario.",
      "Error frecuente",
      "Una caída desde máximos o un múltiplo bajo no crean margen de seguridad. Compara con un rango de valor defendible que cambie con la evidencia.",
    ),
  },
} satisfies EditorialLocaleContent;
