import type { EditorialLocaleContent } from "../types";
import { editorialEntry as e } from "./entry";

export const frEditorialContent = {
  ui: {
    blogEyebrow: "CARNET DE RECHERCHE",
    blogTitle: "Analyser les actions américaines par les preuves",
    blogDescription:
      "Des guides pratiques pour lire les rapports, tester les hypothèses et comparer les entreprises.",
    glossaryEyebrow: "GLOSSAIRE DE L’INVESTISSEUR",
    glossaryTitle: "Des termes financiers vraiment opérationnels",
    glossaryDescription:
      "Définitions claires, limites et pièges fréquents pour mieux mener vos recherches.",
    backToBlog: "Retour au blog",
    backToGlossary: "Retour au glossaire",
    readArticle: "Lire l’article",
    readDefinition: "Voir la définition",
    readNext: "À lire ensuite",
    minutes: "min de lecture",
    updated: "Mis à jour",
    ctaTitle: "Appliquez ce cadre à une entreprise réelle",
    ctaDescription:
      "L’équipe Stocksembly étudie l’entreprise, met la thèse à l’épreuve et conserve les preuves dans un dossier unique.",
    ctaAction: "Lancer une recherche",
    sidebarBlog: "Blog",
    sidebarGlossary: "Glossaire",
  },
  entries: {
    "how-to-read-a-10-k": e(
      "Comment lire un 10-K pour analyser une action",
      "Une méthode reproductible pour passer du modèle économique aux flux de trésorerie, aux risques et aux questions ouvertes.",
      "PUBLICATIONS",
      "Illustration du concept : Comment lire un 10-K pour analyser une action",
      "Commencez par l’activité",
      "Dans l’Item 1, expliquez qui paie, ce qui est acheté et ce qui doit rester vrai pour que le chiffre d’affaires se répète. Segments, concentration clients, canaux et saisonnalité révèlent souvent l’écart entre récit et moteur économique.",
      "Rapprochez bénéfice et trésorerie",
      "Reliez résultat opérationnel, flux opérationnel et flux de trésorerie disponible. Examinez le besoin en fonds de roulement temporaire, les coûts capitalisés, les actions et les ajustements récurrents.",
      "Transformez les risques en signaux",
      "Identifiez le risque qui a changé, celui qui menace le plus la thèse et l’indicateur qui alerterait en premier. Gardez des questions pour les résultats et les concurrents.",
    ),
    "earnings-quality-and-cash-conversion": e(
      "Qualité des bénéfices : tester la conversion en trésorerie",
      "Fonds de roulement, intensité capitalistique et ajustements récurrents peuvent modifier la lecture du bénéfice publié.",
      "FINANCES",
      "Illustration du concept : Qualité des bénéfices : tester la conversion en trésorerie",
      "Définissez le bénéfice à valider",
      "Résultat net, opérationnel, EBITDA et résultat ajusté répondent à des questions différentes. Choisissez la mesure adaptée et rapprochez-la de la trésorerie sur un cycle complet.",
      "Classez l’écart",
      "Séparez créances et stocks liés à la croissance, encaissements anticipés, développement capitalisé, rémunération en actions et acquisitions. Vérifiez si le cash vient de l’exploitation ou d’un recul des investissements.",
      "Concluez sur la durabilité",
      "Estimez une conversion normalisée et précisez le mouvement de bilan qui invaliderait cette lecture.",
    ),
    "how-to-choose-comparable-companies": e(
      "Comment choisir des entreprises vraiment comparables",
      "Le choix des pairs commence par le modèle économique, pas par un tableau de multiples.",
      "VALORISATION",
      "Illustration du concept : Comment choisir des entreprises vraiment comparables",
      "Comparez le moteur économique",
      "Étudiez acquisition clients, prix, reconnaissance du revenu, financement de la croissance et rétention. Des revenus proches ne garantissent pas des économies proches.",
      "Ajustez maturité et capital",
      "Créez un noyau aux croissance, marges, réinvestissements, cyclicité et risque financier proches ; gardez les autres comme références ciblées.",
      "Traitez le multiple comme un résultat",
      "Le multiple reflète les attentes du marché. Vérifiez si l’historique opérationnel justifie la place de l’entreprise.",
    ),
    "bull-base-bear-scenario-analysis": e(
      "Guide des scénarios haussier, central et baissier",
      "Construisez des scénarios avec des hypothèses opérationnelles cohérentes, pas des objectifs de cours arbitraires.",
      "SCÉNARIOS",
      "Illustration du concept : Guide des scénarios haussier, central et baissier",
      "Utilisez un modèle commun",
      "Modifiez les mêmes moteurs : volume, prix, rétention, marge brute, investissement et capital. Le scénario central est le chemin le mieux étayé, pas une moyenne mécanique.",
      "Expliquez le mécanisme",
      "Reliez chaque hypothèse à un événement et à une preuve observable. N’additionnez pas croissance maximale, marge maximale et investissement minimal sans logique économique.",
      "Définissez la mise à jour",
      "Notez le prochain événement important, le signal précoce et l’hypothèse la plus sensible aux nouvelles preuves.",
    ),
    "counterarguments-in-ai-stock-research": e(
      "Pourquoi la recherche boursière par IA exige un contre-argument solide",
      "Plus d’agents ne garantit pas une meilleure analyse : il faut un défi indépendant et une trace des preuves.",
      "PROCESSUS",
      "Illustration du concept : Pourquoi la recherche boursière par IA exige un contre-argument solide",
      "Le consensus peut échouer",
      "Plusieurs modèles peuvent partager la même hypothèse cachée. Répéter la question augmente alors la confiance sans preuve indépendante ; séparez rôles, sources et critères.",
      "Rendez l’alternative réfutable",
      "Le contradicteur présente la meilleure explication rivale, ses preuves et l’observation qui l’infirmerait, puis teste fraîcheur, définitions comptables et causalité.",
      "Publiez le désaccord",
      "Conserver les affirmations supprimées, les questions ouvertes et la raison finale rend les révisions futures auditables.",
    ),
    "free-cash-flow": e(
      "Flux de trésorerie disponible (FCF)",
      "Trésorerie restante après les investissements nécessaires au maintien et à la croissance de l’activité.",
      "TRÉSORERIE",
      "Illustration du concept : Flux de trésorerie disponible (FCF)",
      "Définition",
      "Il correspond généralement au flux opérationnel moins les dépenses d’investissement et approche les fonds disponibles pour dette, acquisitions, rachats, dividendes ou réinvestissement.",
      "Piège fréquent",
      "Le FCF peut monter grâce à un investissement reporté ou à une libération temporaire du fonds de roulement. Rapprochez actions, loyers, acquisitions récurrentes et développement capitalisé.",
    ),
    "ev-to-ebitda": e(
      "EV/EBITDA",
      "Multiple comparant la valeur d’entreprise au résultat avant intérêts, impôts, dépréciation et amortissement.",
      "VALORISATION",
      "Illustration du concept : EV/EBITDA",
      "Définition",
      "La valeur d’entreprise combine capitalisation, dette et trésorerie pour comparer des activités aux financements différents.",
      "Piège fréquent",
      "L’EBITDA ignore investissement et fonds de roulement, et peut faire paraître trop bon marché les entreprises capitalistiques ou acquisitives. Associez-le au FCF.",
    ),
    "earnings-guidance": e(
      "Prévisions de résultats (guidance)",
      "Fourchette ou perspective qualitative donnée par la direction sur revenus, bénéfices, marges ou indicateurs futurs.",
      "ATTENTES",
      "Illustration du concept : Prévisions de résultats (guidance)",
      "Définition",
      "La guidance traduit l’information actuelle en fourchette trimestrielle ou annuelle et peut couvrir revenus, bénéfice ajusté, marge, investissement ou KPI sectoriel.",
      "Analyse",
      "Comparez milieu, largeur, hypothèses et exclusions aux prévisions passées et aux résultats réels. Distinguez changement d’activité et changement de définition.",
    ),
    "share-dilution": e(
      "Dilution des actions",
      "Réduction de la part de chaque actionnaire existant lorsque le nombre effectif d’actions augmente.",
      "PROPRIÉTÉ",
      "Illustration du concept : Dilution des actions",
      "Définition",
      "Actions nouvelles, options, unités restreintes et convertibles augmentent les droits sur la valeur ; valeur totale et valeur par action peuvent évoluer différemment.",
      "Mesure",
      "Suivez actions diluées moyennes et finales, rémunération et convertibles. Comparez croissance totale et par action ainsi que le coût réel des rachats.",
    ),
    "margin-of-safety": e(
      "Marge de sécurité",
      "Coussin entre une valeur estimée prudemment et le prix payé pour absorber incertitude et erreur.",
      "RISQUE",
      "Illustration du concept : Marge de sécurité",
      "Définition",
      "Ce n’est pas une décote fixe. Plus demande, marges, financement, avantage concurrentiel et valorisation sont incertains, plus le coussin requis est généralement large.",
      "Piège fréquent",
      "Une baisse depuis un sommet ou un multiple faible ne crée pas de marge de sécurité. Comparez à une fourchette de valeur défendable qui évolue avec les preuves.",
    ),
  },
} satisfies EditorialLocaleContent;
