import type { EditorialLocaleContent } from "../types";
import { editorialEntry as e } from "./entry";

export const ptBrEditorialContent = {
  ui: {
    blogEyebrow: "CADERNO DE PESQUISA",
    blogTitle: "Análise de ações dos EUA, baseada em evidências",
    blogDescription:
      "Guias práticos para ler documentos, testar premissas e comparar empresas.",
    glossaryEyebrow: "GLOSSÁRIO DO INVESTIDOR",
    glossaryTitle: "Termos financeiros que ajudam na análise",
    glossaryDescription:
      "Definições claras, limites e armadilhas para usar cada conceito com critério.",
    backToBlog: "Voltar ao blog",
    backToGlossary: "Voltar ao glossário",
    readArticle: "Ler artigo",
    readDefinition: "Ver definição",
    readNext: "Leia a seguir",
    minutes: "min de leitura",
    updated: "Atualizado",
    ctaTitle: "Aplique o método a uma empresa real",
    ctaDescription:
      "A equipe Stocksembly investiga a empresa, desafia a tese e preserva as evidências em um único arquivo.",
    ctaAction: "Iniciar pesquisa",
    sidebarBlog: "Blog",
    sidebarGlossary: "Glossário",
  },
  entries: {
    "how-to-read-a-10-k": e(
      "Como ler um 10-K para analisar ações",
      "Um processo repetível para entender o negócio, o caixa, os riscos e as próximas perguntas.",
      "DOCUMENTOS",
      "Relatório anual escuro com marcadores azuis em uma mesa de análise",
      "Comece pelo negócio",
      "No Item 1, explique quem paga, o que compra e o que precisa continuar verdadeiro para a receita se repetir. Segmentos, concentração de clientes, canais e sazonalidade costumam revelar a diferença entre a narrativa e o motor econômico.",
      "Concilie lucro e caixa",
      "Ligue lucro operacional, fluxo operacional e fluxo de caixa livre. Examine capital de giro temporário, custos capitalizados, remuneração em ações e ajustes que voltam todos os anos.",
      "Transforme riscos em sinais",
      "Identifique o risco que mudou, o que mais ameaça a tese e qual indicador avisaria primeiro. Termine com perguntas para resultados e documentos dos concorrentes.",
    ),
    "earnings-quality-and-cash-conversion": e(
      "Qualidade dos lucros: como testar a conversão em caixa",
      "Capital de giro, intensidade de investimento e ajustes recorrentes podem mudar o lucro reportado.",
      "FINANÇAS",
      "Fluxo de caixa transparente passando por um motor operacional escuro",
      "Defina o lucro a validar",
      "Lucro líquido, operacional, EBITDA e lucro ajustado respondem a perguntas diferentes. Escolha a medida adequada e compare-a com caixa durante um ciclo completo.",
      "Classifique a diferença",
      "Separe contas a receber e estoques ligados ao crescimento, recebimentos antecipados, desenvolvimento capitalizado, ações e aquisições. Verifique se o caixa melhorou por operação ou menor investimento.",
      "Conclua sobre durabilidade",
      "Estime uma conversão normal e indique qual mudança no balanço invalidaria a leitura.",
    ),
    "how-to-choose-comparable-companies": e(
      "Como escolher empresas realmente comparáveis",
      "A seleção de pares começa pelo modelo de negócio, não por uma tabela de múltiplos.",
      "VALUATION",
      "Cinco blocos empresariais de vidro medidos, um claramente diferente",
      "Compare o motor econômico",
      "Analise aquisição de clientes, preço, reconhecimento de receita, financiamento do crescimento e retenção. Receita parecida não garante economia parecida.",
      "Ajuste maturidade e capital",
      "Crie um grupo central com crescimento, margens, reinvestimento, ciclo e risco financeiro próximos; use os demais apenas como referência específica.",
      "Trate o múltiplo como resultado",
      "O múltiplo é evidência sobre expectativas de mercado. Teste se o histórico operacional sustenta a posição da empresa.",
    ),
    "bull-base-bear-scenario-analysis": e(
      "Guia de cenários otimista, base e pessimista",
      "Construa cenários com premissas operacionais coerentes, não com preços-alvo arbitrários.",
      "CENÁRIOS",
      "Um caminho analítico azul dividido em três cenários",
      "Use um modelo comum",
      "Altere as mesmas variáveis: volume, preço, retenção, margem bruta, investimento e capital. O caso base deve ser o caminho mais defensável, não uma média automática.",
      "Explique o mecanismo",
      "Ligue cada premissa ao evento que a move e à evidência observável. Não combine crescimento máximo, margem máxima e investimento mínimo sem suporte operacional.",
      "Defina a atualização",
      "Registre o próximo evento relevante, o sinal inicial e a premissa mais sensível a novas evidências.",
    ),
    "counterarguments-in-ai-stock-research": e(
      "Por que pesquisas com IA precisam de um contra-argumento forte",
      "Mais agentes não garantem melhor análise: são necessários desafio independente e trilha de evidências.",
      "PROCESSO",
      "Duas mesas de pesquisa opostas conectadas por um feixe azul",
      "O consenso pode falhar",
      "Vários modelos podem compartilhar a mesma premissa oculta. Repetir a pergunta aumenta confiança sem criar evidência independente; separe papéis, fontes e critérios.",
      "Torne a alternativa falsificável",
      "O crítico deve expor a melhor explicação rival, suas evidências e a observação que a refutaria, além de testar atualidade, definições contábeis e causalidade.",
      "Publique a divergência",
      "Guardar afirmações removidas, dúvidas abertas e a razão final permite auditar revisões futuras.",
    ),
    "free-cash-flow": e(
      "Fluxo de caixa livre (FCF)",
      "Caixa restante após o investimento necessário para manter e expandir o negócio.",
      "CAIXA",
      "Fluxo azul de caixa atravessando um filtro de investimento",
      "Definição",
      "Normalmente é o fluxo operacional menos o investimento de capital e aproxima o caixa disponível para dívida, aquisições, recompras, dividendos ou reinvestimento.",
      "Armadilha comum",
      "Pode subir por investimento adiado ou liberação temporária de capital de giro. Concilie ações, arrendamentos, aquisições recorrentes e desenvolvimento capitalizado.",
    ),
    "ev-to-ebitda": e(
      "EV/EBITDA",
      "Múltiplo que compara valor da empresa com lucro antes de juros, impostos, depreciação e amortização.",
      "VALUATION",
      "Estrutura empresarial equilibrada sobre um motor operacional",
      "Definição",
      "O valor da empresa reúne valor do patrimônio, dívida e caixa para comparar operações com estruturas de financiamento diferentes.",
      "Armadilha comum",
      "EBITDA ignora investimento e capital de giro, podendo baratear artificialmente negócios intensivos em ativos ou aquisições. Use com FCF.",
    ),
    "earnings-guidance": e(
      "Guidance de resultados",
      "Faixa ou perspectiva qualitativa da gestão para receita, lucro, margens ou outras métricas futuras.",
      "EXPECTATIVAS",
      "Pista trimestral escura levando a um farol azul",
      "Definição",
      "O guidance transforma informações atuais em uma faixa para o próximo trimestre ou ano, incluindo receita, lucro ajustado, margem, investimento ou KPI específico.",
      "Como analisar",
      "Compare ponto médio, amplitude, premissas e exclusões com orientações anteriores e resultados reais. Separe mudança do negócio de mudança de definição.",
    ),
    "share-dilution": e(
      "Diluição de ações",
      "Redução da participação de cada acionista quando aumenta o número efetivo de ações.",
      "PROPRIEDADE",
      "Anel azul de propriedade dividido em muitos segmentos",
      "Definição",
      "Novas ações, opções, unidades restritas e conversíveis aumentam os direitos sobre o valor; o valor total pode crescer mais rápido que o valor por ação.",
      "Como medir",
      "Acompanhe ações diluídas médias e finais, remuneração e conversíveis. Compare crescimento total e por ação, além do custo real das recompras.",
    ),
    "margin-of-safety": e(
      "Margem de segurança",
      "Folga entre uma estimativa conservadora de valor e o preço pago para absorver incerteza e erro.",
      "RISCO",
      "Ponte azul de valuation acima de um mercado volátil",
      "Definição",
      "Não é um desconto fixo. Quanto maior a incerteza de demanda, margens, financiamento, vantagem competitiva e avaliação, maior tende a ser a folga necessária.",
      "Armadilha comum",
      "Queda desde a máxima ou múltiplo baixo não criam margem de segurança. Compare com uma faixa de valor defensável que mude com as evidências.",
    ),
  },
} satisfies EditorialLocaleContent;
